# Generated by Django 5.1.1 on 2026-01-27 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='slug может содержать символы: ^[-a-zA-Z0-9_]+$', regex='^[-a-zA-Z0-9_]+$')])),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='slug может содержать символы: ^[-a-zA-Z0-9_]+$', regex='^[-a-zA-Z0-9_]+$')])),
            ],
            options={
                'verbose_name': ('Жанр',),
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('genre', models.ManyToManyField(related_name='genres', to='reviews.genres')),
                ('title', models.ManyToManyField(related_name='titles', to='reviews.genres')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
