# Generated by Django 5.1.1 on 2026-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_categories_genres_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': ('категория',), 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': ('жанр',), 'verbose_name_plural': 'жанры'},
        ),
        migrations.RemoveField(
            model_name='titles',
            name='title',
        ),
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='reviews.genres'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
