# Generated by Django 5.1.1 on 2026-01-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_categories_options_alter_genres_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': ('произведение',), 'verbose_name_plural': 'произведения'},
        ),
    ]
