# Generated by Django 5.1.1 on 2026-01-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_titles_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
    ]
