# Generated by Django 5.1.1 on 2026-01-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_category_slug_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='reviews.category'),
        ),
    ]
