# Generated by Django 5.1.1 on 2026-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_user_bio_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'user'), ('2', 'moderator'), ('3', 'admin')], default='1', max_length=1, verbose_name='Роль'),
        ),
    ]
