# Generated by Django 5.1.1 on 2026-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], default=1, verbose_name='Роль'),
        ),
    ]
