# Generated by Django 5.1.1 on 2026-01-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_remove_title_category_alter_title_genre_and_more'),
        ('reviews', '0017_alter_user_role'),
    ]

    operations = [
    ]
