# Generated by Django 5.1.1 on 2026-01-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_alter_comment_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
