# Generated by Django 5.1.1 on 2026-01-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_user_role'),
        ('reviews', '0022_rename_title_id_review_title'),
    ]

    operations = [
    ]
