# Generated by Django 5.1.1 on 2026-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_merge_20260130_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('moderator', 'Moder')], default='user', max_length=256, verbose_name='Роль'),
        ),
    ]
