# Generated by Django 5.1.1 on 2026-01-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
    ]
