# Generated by Django 5.1.1 on 2026-01-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_rename_review_id_comment_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
