# Generated by Django 5.1.1 on 2026-01-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_alter_comment_options_alter_review_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
