# Generated by Django 5.1.1 on 2026-01-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_user_role'),
        ('reviews', '0027_merge_20260131_1512'),
    ]

    operations = [
    ]
