# Generated by Django 5.2.11 on 2026-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_alter_title_category_alter_title_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(verbose_name='Год выпуска'),
        ),
    ]
