# Generated by Django 5.2.11 on 2026-02-04 12:31

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validators.validate_current_year], verbose_name='Год выпуска'),
        ),
    ]
