# Generated by Django 5.1.1 on 2026-02-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_alter_comment_author_alter_review_author'),
        ('reviews', '0032_alter_title_year'),
    ]

    operations = [
    ]
