# Generated by Django 5.1.1 on 2026-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_alter_title_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
