# Generated by Django 5.1.1 on 2026-02-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_delete_user'),
        ('reviews', '0033_merge_20260205_1215'),
    ]

    operations = [
    ]
